spring.application.name=rating_service

#spring.datasource.url=jdbc:postgresql://postgresql-db-rating:5432/rating_db
spring.datasource.url=jdbc:postgresql://localhost:5432/rating_db?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#user.service.url=http://user-service:8080
user.service.url=http://localhost:8081
#reservation.service.url=http://reservation-service:8080
reservation.service.url=http://localhost:8083

server.port=8084