spring.application.name=rating_service

#spring.datasource.url=jdbc:postgresql://postgresql-db-rating:5432/rating_db
spring.datasource.url=jdbc:postgresql://localhost:5432/rating_db?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

user.service.url=http://user-service:8081
accommodation.service.url=http://accommodation-service:8082
reservation.service.url=http://reservation-service:8083
notification.service.url=http://notification-service:8085

server.port=8084

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=rating-service
management.server.port=8084
otel.exporter.otlp.endpoint=http://jaeger-collector.monitoring.svc.cluster.local:4317
management.tracing.sampling.probability=1.0

loki.url=http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
logging.level.root=INFO
logging.level.org.springframework.web=INFO
